### ISSUE TITLE
[dev] PSD on small FFT size

### ISSUE THREAD

**Issue by nicholascioli** [pwstegman/WebBCI#1]
When using a small FFT size, the PSD returns `NaN`.

Steps to reproduce.
```
bci.signalBandPower([1, 2, 3, 4, 5, 6, 7], 8, 256, 'alpha')
=> NaN
bci.signalBandPower([1, 2, 3, 4, 5, 6, 7], 16, 256, 'alpha')
=> NaN
bci.signalBandPower([1, 2, 3, 4, 5, 6, 7], 32, 256, 'alpha')
=> 26.416893639442556
```

**Comment by pwstegman** [comment]
Thank you, this is now fixed.

The psdBandPower function (which signalBandPower calls) now floors the start and ceils the end indices when selecting the range of buckets from the fourier transform, so there will always be at least one bucket from which an average power can be calculated.
